# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章详细')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章大分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='权限名称')),
                ('type', models.IntegerField(choices=[(1, '管理员'), (2, '普通用户')], verbose_name='权限等级')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章小分类名称')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='app01.Category', verbose_name='文章小分类关联的大分类')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名称')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Role', verbose_name='用户权限')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='app01.Tag', verbose_name='文章所属小类型'),
        ),
    ]
